name: scam_detector
description: Real-time scam call detection mobile app using Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.1
  
  # Audio Recording
  record: ^6.1.0
  permission_handler: ^12.0.1
  
  # UI & State Management
  cupertino_icons: ^1.0.6
  provider: ^6.0.0
  
  # Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  
  # Audio Playback
  audioplayers: ^5.2.0
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.0.1
  google_fonts: ^6.3.3
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.7
  pull_to_refresh: ^2.0.0
  vibration: ^3.1.5
  flutter_launcher_icons: ^0.14.4
  phone_state: ^3.0.1
  flutter_local_notifications: ^19.5.0
  flutter_foreground_task: ^9.2.0
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

flutter_native_splash:
  color: '#000000'
  color_dark: '#000000'
  image: assets/splash/splash_icon.png
  image_dark: assets/splash/splash_icon.png
  android_12:
    image: assets/splash/splash_icon.png
    image_dark: assets/splash/splash_icon.png
    icon_background_color: '#5C6BC0'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#5C6BC0"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  min_sdk_android: 21
